### ISSUE TITLE
Local File Paths for src not working

### ISSUE THREAD

**Issue by iChip** [robinscholz/svelte-inline-svg#13]
According to the README.md, this is a valid src: const src = '/path/to/file.svg'

This won't work for me, so I read through the source and looks like the library supports a url since a fetch request is made, not local file paths as per above.

Please clarify the docs as to  intended usage or add support for local file paths.

**Comment by robinscholz** [comment]
Updated the docs, thanks. Your best bet would probably be to convert your files to a base64 string via [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL).
