### ISSUE TITLE
Could not resolve './utils/forwardEvents'

### ISSUE THREAD

**Issue by flicksolutions** [robinscholz/svelte-inline-svg#22]
Hi there

There seems to be something off in the newest release on npm... ForwardEventsBuilder is imported, but the utils folder does not exist (in the npm-package at least. I see that it does in the main branch).

I'm getting the following node error:
```
Could not resolve './utils/forwardEvents' from node_modules\svelte-inline-svg\src\inline-svg.svelte
node:internal/modules/cjs/loader:944
  throw err;
  ^
```

Thanks a lot for fixing this!

**Comment by robinscholz** [comment]
@flicksolutions Thanks for reporting this. Could you try v1.1.1 and see if the error persists?

**Comment by flicksolutions** [comment]
Thank you, @robinscholz for your swift reaction! It works now!
