### ISSUE TITLE
Clicking on svg shows border

### ISSUE THREAD

**Issue by ghoshsanjoy78** [robinscholz/svelte-inline-svg#29]
I am trying to use svelte-inline-svg on my Sveltekit project. It embeds just fine and shows up on my webpage

However, when I click on the SVG, it shows an ugly black border around the SVG.

How can I get rid of this behavior and not have a border show up on clicking on the SVG ?

**Comment by robinscholz** [comment]
Hi @ghoshsanjoy78,

could you please provide me with a minimal reproduction of the problem?

**Comment by erianvc** [comment]
It is something specific to the browser, some elements when they are in 'focus' mode have an outline,
it can be corrected with CSS but I don't know if it is necessary.

![GIF 21-05-2022 20-29-13](https://user-images.githubusercontent.com/4275190/169674471-1b87706f-bbc0-41c8-b771-29968bc6966f.gif)
