### ISSUE TITLE
Can't compile because "src" is excluded

### ISSUE THREAD

**Issue by tlgreg** [robinscholz/svelte-inline-svg#3]
In `package.json` the `svelte` field refers to `src/index.js` but it is not included in the `files` field so the component can't be compiled in a `rollup-plugin-svelte` (or `svelte-loader`) project.

**Comment by robinscholz** [comment]
@tlgreg Thanks for reporting the issue. Including `src/index.js` in `files` should fix this, correct?

**Comment by robinscholz** [comment]
@tlgreg Should be fixed in `1.0.2`. Could you check if it’s working for you now?

**Comment by hmaesta** [comment]
Not working here... GitHub Actions is failing to find relative path.

![Screen Shot 2020-12-11 at 11 11 56](https://user-images.githubusercontent.com/741969/101920127-2f5c7680-3baa-11eb-9ffc-d2ba825e3214.png)

**Comment by robinscholz** [comment]
Forgot to include the actual `svelte` component within `files` 🙄

Fixed in 1.0.5! If there’s anything else I missed, please open another issue.
