### ISSUE TITLE
contenteditable="true"?

### ISSUE THREAD

**Issue by eriandev** [robinscholz/svelte-inline-svg#30]
I know it's a small thing, but I want to know why rendered SVGs are added `contenteditable="true"`?
All SVG properties should be chosen by the user and not have things that are not necessary by themselves.

**Comment by robinscholz** [comment]
@eriandev Sorry for the late reply. 

I originally wrote the package for a very specific use case before open sourcing it, this is a leftover from back then. Feel free to send a pull request to make this optional.

**Comment by artemjackson** [comment]
Hey @robinscholz 👋 Kindly reminding, please check the [PR](https://github.com/robinscholz/svelte-inline-svg/pull/36)  😉
