### ISSUE TITLE
Trouble rendering SVGs from node modules

### ISSUE THREAD

**Issue by ixxie** [robinscholz/svelte-inline-svg#8]
After you resolved the [previous issue I had with SSR](https://github.com/robinscholz/svelte-inline-svg/issues/6), I now tried to apply `svelte-inline-svg` to my project. I am trying to render SVGs from the [openmoji](https://github.com/hfg-gmuend/openmoji) library.

The library returns the absolute path of the SVG files (stored in the `/node_modules/` folder), and I double checked this is indeed correct; but somehow, I am not managing to render this SVG file. I get no error, but the SVG doesn't render. I'm probably just doing something wrong, and I apologize if I am abusing the issue feature for support, since I am not sure how else to proceed!

I updated [the minimal example repository I used for the previous issue](https://github.com/ixxie/InlineSVG-SSR-Issue) to demonstrate this issue with a minimal example.

**Comment by robinscholz** [comment]
This seems out of scope for this plugin. You can use a rollup plugin to handle importing them directly.
